import { z } from 'zod';
import * as s from '../schemas/index.js';

export const toolSchemas = {
  get_workspace: z.object({}).strict(),
  list_products: s.ListProductsInput,
  get_product: s.GetProductInput,
  list_materials: s.ListMaterialsInput,
  get_material: s.GetMaterialInput,
  list_locations: s.ListLocationsInput,
  list_lots: s.ListLotsInput,
  get_inventory_stock: s.InventoryStockInput,
  list_inventory_movements: s.ListInventoryMovementsInput,
  search_suppliers: s.SearchSuppliersInput,
  get_supplier: s.GetSupplierInput,
  list_purchase_orders: s.ListPurchaseOrdersInput,
  get_purchase_order: s.GetPurchaseOrderInput,
  list_sales_orders: s.ListSalesOrdersInput,
  get_sales_order: s.GetSalesOrderInput,
  get_bom: s.GetBomInput,
  preview_bom_cost: s.PreviewBomCostInput,
  list_production_runs: s.ListProductionRunsInput,
  get_production_run: s.GetProductionRunInput,
  get_production_run_costing: s.ProductionRunIdInput,
  get_production_forecast: s.ProductionForecastInput,
  get_recall_readiness: z.object({}).strict(),
  trace_lot: s.TraceLotInput,
  create_product: s.CreateProductInput,
  update_product: s.UpdateProductInput,
  create_material: s.CreateMaterialInput,
  update_material: s.UpdateMaterialInput,
  create_supplier: s.CreateSupplierInput,
  update_supplier: s.UpdateSupplierInput,
  create_location: s.CreateLocationInput,
  update_location: s.UpdateLocationInput,
  set_default_location: s.SetDefaultLocationInput,
  create_barcode: s.CreateBarcodeInput,
  add_bom_component: s.AddBomComponentInput,
  update_bom_component: s.UpdateBomComponentInput,
  remove_bom_component: s.RemoveBomComponentInput,
  create_purchase_order: s.CreatePurchaseOrderInput,
  mark_purchase_order_ordered: s.MarkPurchaseOrderOrderedInput,
  receive_purchase_order: s.ReceivePurchaseOrderInput,
  create_sales_order: s.CreateSalesOrderInput,
  fulfill_sales_order: s.FulfillSalesOrderInput,
  create_production_run: s.CreateProductionRunInput,
  record_production_receipt: s.RecordProductionReceiptInput,
  transfer_inventory: s.TransferInventoryInput,
  adjust_inventory: s.AdjustInventoryInput,
} as const;
